#create database quanlytintuc;

use quanlytintuc;


CREATE TABLE quyen(
  maquyen bigint NOT NULL PRIMARY KEY auto_increment,
  tenquyen VARCHAR(255) NOT NULL
);

CREATE TABLE taikhoan (
  mataikhoan bigint NOT NULL PRIMARY KEY auto_increment,
  email VARCHAR(255) NULL,
  matkhau VARCHAR(150) NOT NULL,
  maquyen bigint NOT NULL,
  hovaten VARCHAR(255) NOT NULL,
  ngaysinh Date NULL,
  anh VARCHAR(255) NULL,
  trangthai int NOT NULL
);
ALTER TABLE taikhoan ADD CONSTRAINT fk_taikhoan_quyen FOREIGN KEY (maquyen) REFERENCES quyen(maquyen);

CREATE TABLE chude (
  machude bigint NOT NULL PRIMARY KEY auto_increment,
  tenchude VARCHAR(255) NOT NULL
);


CREATE TABLE baiviet (
  mabaiviet bigint NOT NULL PRIMARY KEY auto_increment,
  tieude VARCHAR(255) NOT NULL,
  mataikhoan bigint NULL,
  machude bigint NOT NULL,
  mota TEXT NOT NULL,
  noidung TEXT NOT NULL,
  anhnen VARCHAR(255) NOT NULL,
  ngaydang Date NOT NULL,
  trangthai int NOT NULL
);

ALTER TABLE baiviet ADD CONSTRAINT fk_baiviet_taikhan FOREIGN KEY (mataikhoan) REFERENCES taikhoan(mataikhoan);
ALTER TABLE baiviet ADD CONSTRAINT fk_baiviet_chude FOREIGN KEY (machude) REFERENCES chude(machude);


CREATE TABLE binhluan(
  mabinhluan bigint NOT NULL PRIMARY KEY auto_increment,
  mataikhoan bigint NOT NULL,
  mabaiviet bigint NOT NULL,
  noidung TEXT NOT NULL,
  ngaygui Date NOT NULL
);
ALTER TABLE binhluan ADD CONSTRAINT fk_binhluan_taikhan FOREIGN KEY (mataikhoan) REFERENCES taikhoan(mataikhoan);


insert into quyen(tenquyen) values('admin');
insert into quyen(tenquyen) values('nguoidung');
insert into taikhoan(email ,matkhau ,maquyen ,hovaten ,anh ,trangthai) values('admin@gmail.com','123',1,'Phạm Xuân Toán','https://i.ibb.co/GMbLW63/LOGO.png',1);
insert into taikhoan(email ,matkhau ,maquyen ,hovaten ,anh ,trangthai) values('xuantoan@gmail.com','123',2,'Phạm Xuân Toán','https://i.ibb.co/GMbLW63/LOGO.png',1);
insert into taikhoan(email ,matkhau ,maquyen ,hovaten ,anh ,trangthai) values('thanhtri@gmail.com','123',2,'Lê Thanh Trí','https://i.ibb.co/bJ8LBz4/avatar-06.jpg',1);
insert into taikhoan(email ,matkhau ,maquyen ,hovaten ,anh ,trangthai) values('quocviet@gmail.com','123',2,'Nguyễn Quốc VIệt','https://i.ibb.co/bJ8LBz4/avatar-06.jpg',1);


insert into chude(tenchude) values('Thời sự');
insert into chude(tenchude) values('Giáo dục');
insert into chude(tenchude) values('Thế giới');
insert into chude(tenchude) values('Tài chính-Kinh doanh');
insert into chude(tenchude) values('Sức khỏe');
insert into chude(tenchude) values('Thể thao');



INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Đài Loan báo động vì virus lạ chết người tại Trung Quốc', '1', '3', 'Ít nhất 35 người tại Trung Quốc bị nhiễm loại virus mới lây từ động vật khiến giới chức y tế tại Đài Loan báo động về mầm bệnh nguy hiểm chết người này.', 'Phó giám đốc Trang Nhân Tường của Trung tâm kiểm soát dịch bệnh (CDC) Đài Loan mới đây cảnh báo các phòng thí nghiệm trên hòn đảo phải thiết lập quy trình xét nghiệm chuẩn hóa để xác định loại virus mới tên là Langya henipavirus (LayV), theo hãng CNA ngày 8.8. Việc phân tích chuỗi gien của virus dự kiến sẽ hoàn tất trong khoảng 1 tuần.Cảnh báo được đưa ra sau khi xuất hiện các ca bệnh do mắc LayV tại tỉnh Sơn Đông và Hà Nam của Trung Quốc đại lục gần đây. Ông Trang cho biết có 35 ca bệnh được phát hiện và đa số mắc triệu chứng như sốt cao, mệt mỏi, ho, mất vị giác và giảm tế bào bạch cầu. Chưa có ca nào tử vong nhưng tình hình này đòi hỏi phải được theo dõi thêm, theo ông Trang.Ông Trang nói rằng CDC đang tập trung nghiên cứu đường lây nhiễm và sẽ phối hợp với cơ quan nông nghiệp để kiểm tra liệu các bệnh tương tự có tồn tại trên những loài bản địa tại Đài Loan hay không.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/ihvcpuo/2022_08_09/chuot-chui-9469.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('\'Cuộc chiến sống còn\' của Mỹ từ mối nguy ở eo biển Đài Loan', '1', '3', 'Tình hình căng thẳng ở eo biển Đài Loan đang chỉ ra một rủi ro lớn đối với Mỹ về chip bán dẫn - điều mà Washington đang ra sức ứng phó gần đây.', 'Trưa 8.8, tờ South China Morning Post đưa tin Trung Quốc đại lục tiếp tục tiến hành tập trận ở eo biển Đài Loan sau loạt tập trận mà được cho là nhằm phản ứng chuyến thăm của Chủ tịch Hạ viện Mỹ Nancy Pelosi đến Đài Bắc. Nội dung tập trận tiếp nối bao gồm chống ngầm và tấn công trên biển.Rủi ro không chỉ cho Mỹ.Thời gian qua, việc thúc đẩy sản xuất chip bán dẫn tại Mỹ đã trở thành một trong các chủ điểm nghị sự của những nhân vật hàng đầu trong hệ thống chính trị nước này khi công du châu Á. Trong chuyến thăm Nhật Bản và Hàn Quốc từ ngày 20 - 24.5, Tổng thống Mỹ Joe Biden đã chọn nhà máy sản xuất chip bán dẫn của Samsung ở Hàn Quốc làm nơi viếng thăm đầu tiên. Tương tự, khi đến Đài Loan, bà Pelosi cũng đã làm việc với ông Mark Liu, Chủ tịch Tập đoàn TSMC. Đến nay, cả Samsung và TSMC đều đã xúc tiến xây dựng nhà máy sản xuất chip bán dẫn tại Mỹ. Trong đó, Samsung đã bắt đầu xây dựng một nhà máy sản xuất chip bán dẫn với đầu tư lên đến 17 tỉ USD ở bang Texas (Mỹ) và có thể sẽ mở rộng đầu tư để xây dựng tổng cộng 11 nhà máy sản xuất chip cũng tại Texas với tổng đầu tư lên đến gần 200 tỉ USD. Còn TSMC cũng đã bắt đầu xây dựng nhà máy sản xuất chip với mức đầu tư lên đến 12 tỉ USD ở bang Arizona (Mỹ).', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_09/23a1-6382.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Ukraine cáo buộc Nga định ám sát bộ trưởng quốc phòng, giám đốc tình báo quân đội', '1', '3', 'Cơ quan An ninh Ukraine (SBU) đã bắt giữ hai nghi phạm bị cáo buộc tham gia âm mưu của tình báo Nga nhằm ám sát bộ trưởng quốc phòng và người đứng đầu cơ quan tình báo quân đội của chính quyền Kyiv.', 'Trong thông báo mới, SBU (hoặc SSU) cho hay đã ngăn chặn âm mưu của Nga nhằm vào Bộ trưởng Quốc phòng Alexey Reznikov, Giám đốc Tình báo Quân đội Kyrylo Budanov và một nhà hoạt động nổi tiếng của Ukraine (không nêu tên).Trong số hai nghi phạm, một người ở Luhansk đang thuộc quyền kiểm soát của các lực lượng ly khai thân Nga, và người còn lại là cư dân Kyiv. Nghi phạm ở Luhansk đã đến Ukraine thông qua ngõ Belarus và bị bắt giữ ở thành phố Kovel thuộc miền tây bắc Ukraine cùng với nghi phạm ở Kyiv.SBU vừa trải qua đợt thanh lọc trên diện rộng sau khi Tổng thống Volodymyr Zelensky xử lý ông Ivan Bakanov, người đứng đầu cơ quan này, vì để xảy ra tình trạng nhiều cấp dưới cấu kết Nga.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/bpcguqmv/2022_08_09/bo-truong-1931.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('EU bắt đầu \'siết\' lượng khí đốt tiêu thụ để chuẩn bị cho mùa đông', '1', '3', 'Quy định Liên minh châu Âu đưa ra nhằm cắt giảm 15% lượng khí đốt tiêu thụ trong toàn khối sẽ bắt đầu có hiệu lực vào ngày 9.8.', 'Theo AFP, quy định được Liên minh châu Âu (EU) đưa ra nhằm cắt giảm 15% lượng khí đốt tiêu thụ trong toàn khối để đối phó với cuộc khủng hoảng năng lượng sẽ bắt đầu có hiệu lực vào ngày 9.8.Tuy nhiên, một số nước EU không hoàn toàn tuân thủ nghiêm ngặt quy định này, vốn là \"giảm nhu cầu một cách tự nguyện\".', 'https://image.thanhnien.vn/w2048/Uploaded/2022/tnaztw/2022_08_08/gas-851.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('CIA thừa nhận gia tăng tài lực nhằm vào Trung Quốc', '1', '3', 'Cơ quan Tình báo Trung ương Mỹ (CIA) xác nhận rằng giới tình báo Mỹ gia tăng đầu tư tài chính, nguồn lực nhằm để hiểu và đối phó Trung Quốc một cách tốt hơn.', 'Theo AP ngày 8.8, Phó giám đốc Cơ quan Tình báo Trung ương Mỹ (CIA) David Cohen thừa nhận cơ quan này sẽ gia tăng tài lực tập trung vào Trung Quốc, dù đối phó al-Qaeda và các nhóm cực đoan khác vẫn là một ưu tiên.Giới quan sát cho rằng có một sự xoay trục âm thầm của các cơ quan tình báo khi thuyên chuyển hàng trăm nhân viên sang các vị trí tập trung vào Trung Quốc, bao gồm một số người trước đó từng hoạt động trong lĩnh vực chống khủng bố.Mỹ từ lâu đã lo ngại về những tham vọng chính trị, kinh tế gia tăng của Trung Quốc, cho rằng Bắc Kinh tìm cách gây ảnh hưởng bầu cử ở nước ngoài, tiến hành các chiến dịch gián điệp mạng, bên cạnh những vấn đề khác. Một số chuyên gia còn cho rằng Bắc Kinh sẽ tìm cách tái thống nhất Đài Loan bằng vũ lực.Việc thay đổi những ưu tiên được nhiều cựu sĩ quan tình báo và nghị sĩ từ lưỡng đảng ủng hộ, khi cho rằng động thái này quá chậm. Hạ nghị sĩ Jason Crow, người từng phục vụ trong quân ngũ tại Afghanistan và Iraq, cho rằng Mỹ quá tập trung vào phòng chống khủng bố trong vài năm qua.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/uqvppcvo/2022_08_08/dc-3478.jpg', '2022-08-09', '1');

INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Kiến nghị chi tiếp 1.155 tỉ đồng hỗ trợ thất nghiệp cho người lao động', '1', '1', 'Chính phủ kiến nghị Thường vụ Quốc hội cho phép chi tiếp hơn 1.155 tỉ đồng từ Quỹ Bảo hiểm thất nghiệp (BHTN) để hỗ trợ người lao động bị ảnh hưởng bởi đại dịch Covid-19.', 'Ngày 8.8, Phó thủ tướng Lê Minh Khái ký Nghị quyết về việc báo cáo Ủy ban Thường vụ Quốc hội cho phép tiếp tục chi hỗ trợ lao động bị ảnh hưởng bởi đại dịch Covid-19 từ Quỹ BHTN (gói hỗ trợ 38.000 tỉ đồng).Theo đó, Chính phủ thống nhất trình Ủy ban Thường vụ Quốc hội ban hành kết luận về việc cho phép tiếp tục chi trả hỗ trợ đối với người lao động bị ảnh hưởng bởi đại dịch Covid-19 từ Quỹ BHTN như đề nghị của Bộ LĐ-TB-XH.Tuy nhiên, Bộ LĐ-TB-XH cho hay, trong quá trình xây dựng chính sách do chưa xác định rõ đối tượng được hưởng chính sách trong các đơn vị sự nghiệp và doanh nghiệp thuộc lực lượng vũ trang, đối tượng có tên trong danh sách tham gia BHTN, đối tượng tại các đơn vị sự nghiệp công lập trong các cơ quan nhà nước (đơn vị sự nghiệp thuộc Đài Truyền hình Việt Nam, Đài Tiếng nói Việt Nam...).', 'https://image.thanhnien.vn/w2048/Uploaded/2022/aobohun/2021_10_27/congnhan-7963.jpeg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Làng ĐH Đà Nẵng ‘treo’ 25 năm: Quảng Nam đề nghị chi hơn 4.100 tỉ đồng giải phóng mặt bằng', '1', '1', 'Liên quan đến dự án Làng ĐH Đà Nẵng \'treo\' suốt 25 năm, UBND tỉnh Quảng Nam đề nghị chi hơn 4.100 tỉ đồng để giải phóng mặt bằng dự án.', 'Sáng 9.8, Văn phòng UBND tỉnh Quảng Nam cho biết Chủ tịch UBND tỉnh Lê Trí Thanh đã có văn bản báo cáo về tình hình triển khai dự án Làng ĐH Đà Nẵng trên địa phận TX.Điện Bàn (Quảng Nam) gửi Bộ Kế hoạch - Đầu tư và các bộ, ngành liên quan.Tuy nhiên, đến nay đã qua 25 năm, dự án mới chỉ triển khai được một phần thuộc địa phận TP.Đà Nẵng. Dự án kéo dài đã ảnh hưởng rất lớn đến đời sống nhân dân và công tác quản lý an ninh, trật tự xã hội, xây dựng tại địa phương.Không đủ vốn, sẽ giảm diện tích.Tỉnh Quảng Nam tính toán tổng chi phí giải phóng mặt bằng dự kiến khoảng 333,8 tỉ đồng, suất vốn đầu tư xây lắp và thiết bị với diện tích 50 ha khoảng 482 tỉ đồng. Cộng lại, tốn khoảng 815,8 tỉ đồng.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/jbvunuc/2022_08_09/dai-hoc-7675.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Bộ trưởng Công an: 1.300 GB dữ liệu cá nhân người Việt bị mua bán trên mạng', '1', '1', 'Bộ trưởng Công an Tô Lâm cho hay, số lượng dữ liệu cá nhân bị thu thập, mua bán trái phép phát hiện được lên tới gần 1.300 GB, trong đó có nhiều dữ liệu cá nhân nội bộ, nhạy cảm.', 'Lộ dữ liệu cá nhân diễn ra phổ biếnLiên quan tới vấn đề bảo mật thông tin cá nhân, Bộ trưởng Công an Tô Lâm cho hay, dữ liệu cá nhân của khoảng hơn 2/3 dân số Việt Nam (hơn 68 triệu người sử dụng internet) đang được lưu trữ, đăng tải, chia sẻ và thu thập trên internet với nhiều hình thức và mức độ chi tiết khác nhau.Bộ trưởng Công an dẫn chứng chỉ trong 2 năm từ năm 2019 đến năm 2020, Bộ Công an phát hiện hàng trăm cá nhân, tổ chức liên quan bán dữ liệu cá nhân. Một số đường dây chiếm đoạt, mua bán dữ liệu quy mô lớn tại Việt Nam đã bị phát hiện, đấu tranh, xử lý.Xây dựng Nghị định Bảo vệ dữ liệu cá nhân', 'https://image.thanhnien.vn/w2048/Uploaded/2022/nokvrb/2022_02_15/to-lam-5290.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Thu phí đậu ô tô dưới lòng đường: \'Đầu gấu\' ngang nhiên thu phí', '1', '1', 'Không chỉ tiền thu phí đỗ ô tô bị xà xẻo, nhiều bãi thu phí đỗ ô tô tại trung tâm Q.1 (TP.HCM) do Công ty TNHH MTV dịch vụ công ích TNXP TP.HCM thu phí đã bị “đầu nậu” ngang nhiên đứng ra thu phí... như thách thức cơ quan công quyền', '“Đầu gấu” thu phí tại bãi xe của TNXP. Điển hình, tại bãi thu phí đỗ ô tô trên đường Phan Chu Trinh (điểm đầu Lê Thánh Tôn, điểm cuối Lê Lợi, P.Bến Thành - đỗ bên phải, Q.1), nhiều ngày liền, chúng tôi ghi nhận không có bóng dáng lực lượng TNXP làm nhiệm vụ thu phí mà thay vào đó là “đầu gấu” xăm trổ, tóc vàng đứng ra công khai thu tiền. Lúc 10 giờ 30 ngày 1.8, một ô tô tấp vào đậu gần bãi thu phí đỗ ô tô nói trên, thì lập tức bị một thanh niên mặc quần sọt, áo thun trắng, tóc vàng đến đuổi đi và yêu cầu đưa xe vào bãi đỗ.Theo ghi nhận tại thời điểm xe chúng tôi vào bãi, hai bên bãi xe thu phí này đông kín hơn 20 ô tô đậu nối liền nhau. Điều lạ là đều do những người mặc đồ thường và nhóm ông Phong đứng ra thu, hoàn toàn không có bóng dáng lực lượng TNXP dù tuyến đường này được quy định thu phí theo giờ (ngày lẻ và chẵn tương ứng với bên trái và phải).', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_08/554095-8-3593.jpg', '2022-08-09', '1');

INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Lưu ý khẩn về đăng ký nguyện vọng xét tuyển đại học', '1', '2', 'Ngày 9.8, ông Võ Thiện Cang, Trưởng phòng khảo thí và kiểm định chất lượng giáo dục Sở GD-ĐT TP.HCM thông tin về tình hình đăng ký nguyện vọng xét tuyển đại học (ĐH) của thí sinh tại TP.HCM trên hệ thống đăng ký.', 'Ông Cang cho hay trên hệ thống đã xác nhận có 180.823 nguyện vọng xét tuyển ĐH đã được đăng ký.Vì vậy, Sở GD-ĐT khuyến cáo thí sinh thực hiện đăng ký xét tuyển trước hạn cuối (trước 17 giờ ngày 20.8) để tránh các rủi ro về kỹ thuật (nếu có).', 'https://image.thanhnien.vn/w2048/Uploaded/2022/krlqcqjwq/2022_08_09/hinh-dknv-8917.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Một trường CĐ có điểm trúng tuyển phương thức thi tốt nghiệp cao nhất tới 31 điểm', '1', '2', 'Sáng 9.8, Trường CĐ Kỹ thuật Cao Thắng công bố điểm chuẩn trúng tuyển theo phương thức xét điểm thi tốt nghiệp THPT năm 2022, cao nhất là 31 điểm.', 'Tiến sĩ Lê Đình Kha, Hiệu trưởng Trường CĐ Kỹ thuật Cao Thắng, cho biết tính đến ngày 6.8, tổng số thí sinh nộp hồ sơ xét tuyển bằng phương thức sử dụng kết quả điểm thi tốt nghiệp THPT năm 2022 vào trường là gần 4.000 thí sinh. Trong khi đó, chỉ tiêu cho phương thức này là 1.575, chiếm 35% so với lượng hồ sơ nộp vào. Vì thế, điểm chuẩn trúng tuyển của một số ngành là khá cao.\"Những ngành dẫn đầu về số lượng hồ sơ và thí sinh, có mức điểm cao vẫn là công nghệ kỹ thuật ô tô, công nghệ kỹ thuật cơ khí, công nghệ thông tin, bảo trì - sửa chữa ô tô\", tiến sĩ Kha thông tin.\"Những ngành dẫn đầu về số lượng hồ sơ và thí sinh, có mức điểm cao vẫn là công nghệ kỹ thuật ô tô, công nghệ kỹ thuật cơ khí, công nghệ thông tin, bảo trì - sửa chữa ô tô\", tiến sĩ Kha thông tin.\"Những ngành dẫn đầu về số lượng hồ sơ và thí sinh, có mức điểm cao vẫn là công nghệ kỹ thuật ô tô, công nghệ kỹ thuật cơ khí, công nghệ thông tin, bảo trì - sửa chữa ô tô\", tiến sĩ Kha thông tin.Theo tiến sĩ Kha, trường đang xét tuyển bổ sung 9 ngành nghề gồm công nghệ kỹ thuật điện - điện tử, công nghệ kỹ thuật nhiệt (cơ điện lạnh), công nghệ kỹ thuật cơ điện tử, công nghệ kỹ thuật điện tử - viễn thông, kế toán tin học (kế toán doanh nghiệp), hàn (công nghệ cao), điện công nghiệp, điện tử công nghiệp và quản trị mạng máy tính.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/tfxbflu/2022_08_09/img-0796-4179.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('61 học sinh không trúng tuyển lớp 10 ở huyện đảo Lý Sơn sẽ về đâu?', '1', '2', 'Năm nay, Trường THPT Lý Sơn được giao chỉ tiêu tuyển 249 thí sinh vào lớp 10. Tổng số thí sinh đăng ký dự thi là 310. Kết quả chỉ tuyển 249 thí sinh, còn 61 không trúng tuyển lớp 10.', 'Đó là một tỷ lệ “trượt” khó tin, vì nó quá lớn đối với một huyện đảo tiền tiêu như Lý Sơn.Vậy 61 em trượt vào lớp 10 sẽ về đâu?Trong khi Lý Sơn có Trường THPT, và trường này đủ khả năng đưa 61 em học sinh này vào một lớp 10 đặc biệt do trường chịu trách nhiệm dạy dỗ các em trong 3 năm học THPT, để các em có thể vượt qua được kỳ thi tốt nghiệp THPT. Trong 3 năm học đó, những giáo viên của Trường THPT Lý Sơn sẽ hết sức tận tâm để dạy cho các em theo kịp chương trình THPT và đạt kết quả thi THPT tốt nhất. Sau đó sẽ tính tiếp. Không việc gì phải thành lập một “phân hiệu GDTX” hài hước như vậy để dạy cho những em học sinh trên hòn đảo tiền tiêu này.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_08/anh-3-8641.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Học sinh lớp 1 tựu trường sớm 2 tuần trước khai giảng', '1', '2', 'Năm học tới, Bộ GD-ĐT cho phép học sinh lớp 1 tựu trường sớm hơn 2 tuần so với ngày khai giảng và sớm hơn 1 tuần so với các khối lớp khác. Điều này được đánh giá là rất cần thiết.', 'Những “tuần 0” cực kỳ cần thiếtKhi kiểm tra tại các địa phương, ghi nhận đề nghị của các nhà trường về việc cần cho HS đầu cấp tựu trường sớm hơn để có thời gian làm quen với môi trường học tập hoàn toàn mới trước khi vào học chính thức, ông Nguyễn Hữu Độ, Thứ trưởng Bộ GD-ĐT, hứa sẽ xem xét và có thể từ năm học tới sẽ cho HS lớp 1 tựu trường sớm hơn so với các khối lớp còn lại. Đây là những “tuần 0” ngoài 35 tuần thực học, giúp HS các lớp đầu cấp có 2 tuần làm quen lớp, quen trường, thầy cô giáo và bạn bè mới; giúp các em không bỡ ngỡ khi thay đổi môi trường và cách thức học tập mới.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_08/a1-2028.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Vì sao Bộ GD-ĐT đề xuất chưa tăng học phí, trường vẫn tăng?', '1', '2', 'Bộ GD-ĐT có kiến nghị chưa áp dụng mức học phí mới cho năm học 2022 - 2023 nhưng nhiều trường ĐH vẫn dự kiến tăng mạnh so với năm trước đó.', 'Đặc biệt nhóm các trường tự chủ hoàn toàn, học phí (HP) dự kiến tăng thêm hàng chục triệu đồng. Vì sao các trường có thông báo như vậy?Nhưng đến thời điểm này, trong đề án tuyển sinh năm 2022 nhiều trường công bố lộ trình tăng mạnh HP dự kiến cho sinh viên (SV) nhập học năm học 2022 - 2023 so với năm học trước đó.Trong đề án tuyển sinh, Trường ĐH Kinh tế TP.HCM cũng đưa lộ trình HP với SV trúng tuyển khóa mới. Cụ thể, HP chương trình chuẩn năm học 2022 - 2023 với SV mới khoảng 26,5 triệu đồng/năm (830.000 đồng/tín chỉ). Như vậy, so với HP của năm học trước đó ở mức 20,5 triệu đồng/năm thì HP chương trình chuẩn SV khóa mới tăng thêm 5 triệu đồng. HP đối với các khóa học tuyển sinh trước 2022 giữ nguyên mức từ năm 2020 (20,5 triệu/năm).', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_08/anh-4-3171.jpg', '2022-08-09', '1');

INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Giá xăng dầu hôm nay 9.8.2022: Xăng trong nước có thể xuống 21.000 đồng/lít?', '1', '4', 'Đà giảm giá dầu thế giới chưa dứt. Trong nước, giá xăng nhập khẩu về mốc 100 USD/thùng, dự báo giá xăng dầu tại kỳ điều hành tới (11.8) giảm mạnh.', 'Giá xăng dầu thành phẩm trên thị trường Singapore giảm sâu trong tuần qua. Dữ liệu từ Bộ Công thương cho thấy, giá xăng nhập khẩu từ Singapore tính đến ngày 7.8 giảm về mức 100 USD/thùng đối với xăng E5 RON 92, về 103,67 USD/thùng đối với xăng RON 95, dầu diesel 124,34 USD/thùng, dầu hỏa 122 USD/thùng.Đây là mức giá thấp nhất trong vòng 7 tháng qua, tương đương giá nhập khẩu ngày 26.1.2022 với xăng E5 RON 92 là 100 USD/thùng, xăng RON 95 là 101,85 USD/thùng. Như vậy, nếu trừ đi thuế bảo vệ môi trường là 3.300 đồng thì giá xăng nhập hiện chỉ ở mức hơn 21.000 đồng/lít.Tính từ đầu năm đến nay, giá xăng dầu trong nước đã có 20 lần điều chỉnh, trong đó có 13 lần tăng và 7 lần giảm. Tại kỳ điều chỉnh giá gần đây ngày 1.8, giá bán lẻ xăng E5 RON 92 về không quá 24.620 đồng/lít; xăng RON 95 không quá 25.600 đồng/lít; giá dầu diesel 0.05S còn 23.900 đồng/lít, giá dầu hỏa không cao hơn 24.530 đồng/lít, giá dầu mazut 180CST 3.5S không cao hơn 16.540 đồng/kg.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/ohununh/2022_01_22/oil-pump-jacks-work-at-sunset-near-midland-texas-anh-reuters-43.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Vì sao bầu Đức lãi khủng: Sở hữu vườn sầu riêng lớn nhất thế giới', '1', '4', 'Lần đầu tiên sau nhiều năm giấu kín, bầu Đức tiết lộ những \"vũ khí\" bí mật của mình...', 'Đầu năm 2021, khi bàn giao Công ty HAGL Agrico (HNG) cho ông Trần Bá Dương, Chủ tịch Công ty Thaco, câu hỏi lớn nhất của các nhà đầu tư, cổ đông và cả những người yêu mến, quan tâm đến bầu Đức là \"Hoàng Anh Gia Lai còn lại gì, đặc biệt ở Lào, Campuchia?\".Hệ sinh thái nông nghiệp 20.000 hectaVà những gì chúng tôi nhìn thấy, thật sự đáng kinh ngạc. Chỉ trong vòng chưa đầy 2 năm kể từ khi bàn giao HNG, bầu Đức đã gây dựng lên một hệ sinh thái nông nghiệp khép kín cực lớn ở cả Việt Nam, Lào, Campuchia với tổng quỹ đất hơn 20.000 hecta. Cũng chỉ trong vòng 2 năm, gần 7.000 hecta chuối đã được ông bầu bóng đá nổi tiếng nhất Việt Nam trồng xuống, nối một dải xanh ngút ngàn từ Gia Lai qua Lào kéo sang Camphuchia. Hệ thống đường nội bộ được mở khắp các cánh đồng mênh mông, một số tuyến được trải bê tông nên việc đi lại, chuyên chở hàng hóa, vật tư nông nghiệp hết sức thuận tiện. Chuối trồng đến đâu, hệ thống tưới tự động theo tới đó, cung cấp nước, dưỡng chất cho cây trái. 5 nhà máy sấy chuối mới xây dựng với hàng chục nhà máy đóng gói nằm ngay trong vùng nguyên liệu. Chuối thu hoạch được chuyển về nhà máy bằng hệ thống ròng rọc, phương pháp mà bầu Đức là người đầu tiên áp dụng trong ngành công nghiệp chuối tại Việt Nam, Lào, Campuchia học hỏi từ mô hình của \"ông trùm chuối\" thế giới Philippines. Ở đây, công nhân sẽ rửa, phân loại, đóng thùng. Những nải đạt tiêu chuẩn xuất khẩu sẽ đưa vào kho lạnh bảo quản. Hiện toàn bộ chuối trồng ở Lào được xuất bán cho Nhật Bản, Hàn Quốc và Trung Quốc theo đường chính ngạch. Mỗi ngày ở Lào, trung bình 10 container chuối của HAGL được xuất đi và số lượng này tăng từng ngày do chuối trồng cuốn chiếu, mở rộng liên tục nên thu hoạch cũng cuốn chiếu. Khi chúng tôi có mặt tại Attapeu, các xe tải lớn mang biển số Trung Quốc đang \"ăn hàng\". Nhiều năm nay, chuối của HAGL đã ngập tràn Đại Liên, Thượng Hải, Bắc Kinh. Tài xế người Trung Quốc cho biết, xe này sẽ chạy thẳng về Thượng Hải giao hàng. Riêng chuối thải sẽ đưa sang nhà máy sấy xử lý và chuyển về Việt Nam nuôi heo. Với hiệu quả của mô hình heo ăn chuối, tốc độ phát triển của đàn heo đang tăng lên rất nhanh nên thậm chí có một số vùng trồng theo bầu Đức, là dành để nuôi heo toàn bộ, không chỉ chuối thải loại.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/bqmvlcvo/2022_08_08/cuoihag-6013.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Giá vàng hôm nay 9.8.2022: Tăng khoảng 200.000 đồng mỗi lượng', '1', '4', 'Nỗi lo ngại suy thoái kinh tế Mỹ giảm đi nhưng bóng ma lạm phát quay trở lại khiến giá vàng tăng nhanh.', 'Vàng miếng SJC hôm nay tăng 100.000 - 200.000 đồng mỗi lượng, Eximbank mua vào với giá 66,4 triệu đồng/lượng, bán ra 67,4 triệu đồng/lượng; Công ty vàng bạc đá quý Mi Hồng mua với giá 66,5 triệu đồng/lượng, bán ra 67,25 triệu đồng/lượng... Đà tăng giá của vàng trong nước không nhanh bằng quốc tế giúp kéo ngắn khoảng cách chênh lệch giữa giá trong và ngoài nước. Giá vàng thế giới thấp hơn vàng miếng SJC 16,7 triệu đồng/lượng.Giá kim loại quý trên thị trường quốc tế tăng 14 USD/ounce, lên 1.789 USD/ounce. Nền kinh tế Mỹ tăng 528.000 việc làm, tỷ lệ thất nghiệp giảm xuống còn 3,5% và tăng trưởng thu nhập vượt mức 5,2% so với cùng kỳ năm ngoái đã xoa dịu nỗi lo suy thoái kinh tế khi GDP 2 quý liên tiếp của Mỹ âm. Điều này, cùng với sự phát triển mạnh mẽ của lĩnh vực dịch vụ và người tiêu dùng Mỹ có lượng tiền mặt lớn hơn bình thường trong tài khoản séc và quỹ thị trường tiền tệ, trị giá khoảng 3.000 tỉ USD, tất cả cho thấy có rất nhiều áp lực lạm phát trong hệ thống.Tuần này, sự chú ý sẽ đổ dồn vào báo cáo lạm phát tháng 7 của Mỹ, với các nhà kinh tế dự báo tốc độ lạm phát hàng năm sẽ ở mức 8,7% sau khi tăng lên 9,1% vào tháng 6. Các nhà kinh tế kỳ vọng lạm phát cơ bản hàng năm sẽ tăng tốc lên 6,1% sau khi đạt mức 5,9% vào tháng 6. Chỉ số CPI sẽ cho nhà đầu tư thấy rõ hơn hành động của Fed có tăng lãi suất thêm 0,75% trong tháng tới hay không. Đối với vàng, điều này có thể có nghĩa là một sự đảo ngược đáng kể đưa giá từ dưới 1.700 USD/ounce lên gần 1.800 USD/ounce.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/cqjwqgdjw/2022_03_11/f67d1d40-763b-4764-ab88-ce618e24e4e0-8340.jpeg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Dự án nghìn tỉ, giải ngân 0 đồng', '1', '4', 'Chậm giải ngân vốn đầu tư công là câu chuyện dài kỳ nhiều năm nay khiến Quốc hội, Chính phủ sốt ruột.', 'Đặc biệt, những thời điểm quan trọng như hiện nay, tỷ lệ giải ngân thấp sẽ khó tạo động lực cần thiết cho nền kinh tế cần tăng tốc phục hồi sau dịch.Vẫn căn bệnh “trầm kha”, các công trình giao thông trọng điểm luôn là những cái tên góp mặt trong danh sách các dự án có tỷ lệ giải ngân cực thấp tại TP.HCM. Theo ông Nguyễn Hoàng Hải, Giám đốc Kho bạc Nhà nước TP, rất nhiều dự án hạ tầng, giao thông lớn hiện có tỷ lệ giải ngân dưới 10%, như: Công trình hầm chui nút giao thông Nguyễn Hữu Thọ - Nguyễn Văn Linh bố trí 200 tỉ đồng, mới giải ngân được 9,3 tỉ đồng, đạt dưới 5%; Xây dựng nút giao thông An Phú bố trí 375 tỉ đồng, giải ngân 14 tỉ đồng, đạt 4%. Dự án vệ sinh môi trường TP giai đoạn 1 bố trí 1.990 tỉ đồng, giải ngân được 73 tỉ đồng, đạt 4%; Dự án xây dựng hạ tầng, cải tạo môi trường Kênh Tham Lương - Bến Cát - Rạch Nước Lên bố trí 1.039 tỉ đồng hay dự án metro tuyến số 2 (Bến Thành - Tham Lương) cũng giải ngân rất thấp.Theo bà Lê Thị Huỳnh Mai, Giám đốc Sở KH-ĐT TP.HCM, nguyên nhân của việc chậm trễ giải ngân vốn đầu tư công do bồi thường giải phóng mặt bằng chậm khiến hầu hết dự án chậm tiến độ. Liên quan đến trách nhiệm của Sở TN-MT, Phó giám đốc Sở Trần Văn Bảy lý giải từ năm 2021, Sở TN-MT đã đẩy nhanh tiến độ giải quyết thẩm định giá, đến nay đã giải quyết tất cả các hồ sơ thẩm định giá quận huyện chuyển về. Từ tháng 1 - 7.2022, Sở đã thông qua được 52 dự án về giá bồi thường, không còn hồ sơ tồn đọng. Qua rà soát, sở này nhận thấy dự án tắc ở khâu các quận huyện. Thậm chí, Sở TN-MT phải tự rà soát các dự án đầu tư công của quận huyện và nhắc nhở khẩn trương trình hồ sơ thẩm định giá. Pháp lý dự án hoàn thiện rất chậm, hồ sơ cũng không hoàn thiện nên sở phải trả tới trả lui rất mất thời gian.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_09/benh-vien-nhi-dong-thanh-pho-dang-theo-doi-khoang-100-tre-day-thi-som-anh-thuy-hang-8196.jpg', '2022-08-09', '1');

INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Ăn nhiều đường có làm tăng nguy cơ ung thư?', '1', '5', 'Tôi nghe nói ăn nhiều đường có thể làm tăng nguy cơ ung thư, xin hỏi bác sĩ điều này có đúng không? (Q.Trâm, 38 tuổi, ở Quảng Ngãi).', 'PGS-TS-BS Lâm Vĩnh Niên, Trưởng khoa Dinh dưỡng tiết chế, Bệnh viện Đại học Y Dược TP.HCM, trả lời:Ngoài ra, Hội đồng Nghiên cứu Y tế và sức khỏe Quốc gia Úc (NHMRC) đã xem xét tất cả các bằng chứng hiện có để cập nhật Hướng dẫn Chế độ ăn uống của quốc gia này và kết luận rằng việc tiêu thụ đường không liên quan đến việc tăng nguy cơ ung thư. Đã có đầy đủ bằng chứng để kết luận rằng không có mối liên quan giữa đường và ung thư tuyến tụy, ruột, vú và bàng quang. Không có bằng chứng về mối liên hệ trực tiếp giữa tiêu thụ đường và tăng nguy cơ ung thư ở bất kỳ loại nào, theo Cancer Council.Hội đồng trên khuyến khích ăn uống lành mạnh và duy trì trọng lượng cơ thể khỏe mạnh để giúp bảo vệ chống lại bệnh ung thư. Khuyến nghị mọi người thưởng thức đa dạng thực phẩm từ năm nhóm thực phẩm mỗi ngày. Tuy nhiên nên hạn chế ăn các loại thực phẩm chế biến sẵn có chứa thêm đường như bánh quy, bánh ngọt, nước ngọt có đường, rượu bia, nước tăng lực và đồ uống thể thao.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/hfrqy/2022_08_05/anh-chup-man-hinh-2022-08-05-luc-15-50-51-3826.png', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Dấu hiệu tiết lộ bạn có thể bị tiền tiểu đường, đi khám ngay còn kịp', '1', '5', 'Bệnh tiểu đường là bệnh mạn tính hiện chưa có cách chữa trị dứt điểm. Tuy nhiên, nếu nhận biết sớm các dấu hiệu của giai đoạn tiền tiểu đường, chúng ta có thể kịp thời ngăn ngừa bệnh tiểu đường.', 'Tiền tiểu đường là gì?Chỉ khi người bị tiền tiểu đường không thay đổi thói quen ăn uống và tập thể dục, mới phát triển thành tiểu đường.Ngoài ra, một trong những dấu hiệu chính của tiền tiểu đường là phát ban - có thể xuất hiện ở nhiều vị trí khác nhau trên cơ thể, từ tai đến chân.3. Hoại tử mô mỡ do tiểu đường (Necrobiosis lipoidica diabeticorum): Tình trạng này dẫn đến các vùng da màu nâu đỏ, phổ biến nhất là ở cẳng chân. Đặc trưng bởi các mảng da nổi lên, bóng và đỏ với ở chính giữa màu vàng, thường xảy ra ở phụ nữ', 'https://image.thanhnien.vn/w2048/Uploaded/2022/lxwpcqjwp/2022_08_04/sk040801-anh-1-1403.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Nên đi bộ bao nhiêu để giảm nguy cơ mắc bệnh tim?', '1', '5', 'Theo Tổ chức Y tế thế giới (WHO), bệnh tim là nguyên nhân gây tử vong hàng đầu trên toàn thế giới và gây ra khoảng 17,9 triệu ca tử vong mỗi năm.', 'Theo WHO, chế độ ăn uống không lành mạnh, ít vận động, sử dụng thuốc lá và rượu bia là một số thói quen phổ biến nhất gây bệnh tim và đột quỵ.Thực hiện đúng cách, nó có thể là chìa khóa để giảm cân, giảm huyết áp và cholesterol, tăng cường trí nhớ, giảm nguy cơ mắc bệnh tim, tiểu đường, ung thư, Trường Y Harvard viết trong bài đánh giá của mình.Vai trò của đi bộ trong việc cải thiện sức khỏe tim mạch', 'https://image.thanhnien.vn/w2048/Uploaded/2022/wsxrxqeiod/2022_07_26/di-bo-2168.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Đau lưng kéo dài dẫn đến liệt chân, đi khám phát hiện u tủy', '1', '5', 'Nam bệnh nhân 32 tuổi, ở TP.HCM, đau lưng kéo dài nhiều tháng nay nhưng nghĩ là đau cơ thông thường nên chỉ điều trị giảm đau, sau đó 2 chân yếu dần, liệt, đi lại khó khăn.', 'Ngày 9.8, ThS.BS. Trần Vũ Hoàng Dương - Trưởng khoa Sọ não cột sống 2, Bệnh viện đa khoa Xuyên Á cho biết, sau nhận định đánh giá tình trạng ban đầu, các bác sĩ quyết định phẫu thuật vi phẫu lấy u tủy cấp cứu cho bệnh nhân.ThS.BS. Trần Vũ Hoàng Dương khuyến cáo khi xuất hiện đau lưng kéo dài không đáp ứng với điều trị giảm đau thông thường, đặc biệt là ở người trẻ thì nên đến các cơ sở khám chữa bệnh uy tín để khám chuyên khoa, tránh trường hợp để lâu có thể gây tổn thương chức năng vận động, điều trị sẽ mất nhiều thời gian và tỷ lệ hồi phục thấp hơn.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/hfrqy/2022_08_09/298030418-2270341683132994-2052475010621960367-n-1760.jpeg', '2022-08-09', '1');

INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Góc khuất của chàng đội trưởng U.19 Việt Nam', '1', '6', 'Theo dõi U.19 Việt Nam thi đấu, người hâm mộ tỏ ra rất hào hứng và không ít lần dành lời khen cho cầu thủ mang băng đội trưởng, khoác chiếc áo số 10.', 'Sở hữu kỹ thuật cá nhân tốt, có kèo trái khéo léo, cùng với đó là tư duy chiến thuật sắc bén đã giúp Khuất Văn Khang tạo ấn tượng đậm nét trong lòng khán giả.Năm 11 tuổi, Khuất Văn Khang trúng tuyển vào lò đào tạo Viettel từ một trung tâm vệ tinh ở Sơn Tây. Tuy nhiên, khi nhận tin trúng tuyển vào một trong những lò đào tạo bóng đá chất lượng hàng đầu Việt Nam thì cũng là lúc gia đình của Khang lẫn lộn buồn vui. Ít có bậc cha mẹ nào đành lòng nhìn đứa con trai út mới học xong bậc tiểu học phải rời xa gia đình. Phải suy nghĩ rất nhiều, bố mẹ của Khang mới quyết định để con trai theo đuổi đam mê quần đùi áo số.Là một cầu thủ có năng khiếu, tư chất tốt và được đánh giá cao về mặt chuyên môn nhưng Khuất Văn Khang cũng từng trải qua một bài học nhớ đời. Cầu thủ sinh năm 2003 cười ngượng: \"Kỷ niệm mà em không bao giờ quên đó là khi em bị kỷ luật rất nặng vì trốn chơi game. Lúc đó, các lãnh đạo đã họp để đưa ra hình thức kỷ luật, khiển trách và cho em nghỉ tập rất lâu. Từ đó, em đã ý thức được và nghiêm túc hơn trong việc tập luyện, tự nhủ rằng sẽ không để những yếu tố bên ngoài làm ảnh hưởng đến con đường theo đuổi đam mê bóng đá của mình nữa\".', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_08/20a4-6943.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Messi “bắn tin” về khả năng trở lại Barcelona sau khi lập siêu phẩm', '1', '6', 'Một thành viên thân cận với Lionel Messi vừa lên tiếng về khả năng siêu sao người Argentina trở lại Barcelona.', 'Một trong những thành viên trong đoàn tùy tùng của Messi đã phủ nhận tất cả những tin đồn được đưa ra trong những ngày gần đây sau khi cầu thủ của PSG xuất hiện ở Barcelona ở đợt nghỉ phép. Trước đó, chủ tịch Joan Laporta đã công khai bày tỏ việc muốn Messi trở lại. Tuy nhiên, cuộc đàm phán vẫn chưa đặt lên bàn giữa 2 CLB.Những tin đồn về khả năng trở lại Barcelona trong mùa giải tới của Messi xuất hiện dồn dập trong những ngày qua khi đội trưởng tuyển Argentina sẽ kết thúc hợp đồng với PSG vào tháng 6.2023. Tuy nhiên, tờ Mundo Deportivo đã tiếp cận được từ những nguồn tin thân cận nhất của Messi cho rằng hiện tại anh không có liên hệ nào với Barcelona.Về phần Joan Laporta, vị chủ tịch không giấu giếm chuyện ông khẳng định mình có \"mắc nợ\" với Messi, những lời mà ông đã lặp đi lặp lại hơn 2 lần. \"Tôi sẽ không nói thêm về Messi vì anh ấy là cầu thủ của PSG. Tôi sẽ chỉ nói rằng chúng tôi có duyên nợ với anh ấy”, chủ tịch của Barcelona chia sẻ.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/cjhwpdhnw/2022_08_09/messi-afp-7575.jpeg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('Đại chiến U.19 Việt Nam và U.19 Thái Lan: Thầy trò HLV Đinh Thế Nam chọn ai?', '1', '6', 'Hôm nay, tại Bình Dương diễn ra lượt trận cuối cùng vòng loại giải U.19 quốc tế Thanh Niên lần 4 - 2022 giữa U.19 Malaysia với U.19 Myanmar (16 giờ), U.19 Thái Lan với U.19 Việt Nam (18 giờ 30) nhằm xác định đối thủ của đội chủ nhà ở chung kết.', 'Cả 2 trận đấu này được trực tiếp trên FPT Play và YouTube thể thao 360 Báo Thanh Niên.Cục diện giải đấu trước lượt trận cuối như sau: U.19 Việt Nam đã chắc suất vào chung kết sau 2 trận thắng (6 điểm, hiệu số 4/1), U.19 Myanmar sẽ phải tranh hạng ba sau 2 trận thua (0 điểm, hiệu số 0/3). Tấm vé còn lại vào chung kết là cuộc cạnh tranh giữa U.19 Thái Lan (4 điểm, hiệu số 1/0), U.19 Malaysia (1 điểm, hiệu số 1/2). Chỉ cần không thua U.19 Việt Nam ở lượt cuối, U.19 Thái Lan sẽ vào chung kết mà không quan tâm kết quả trận còn lại giữa U.19 Malaysia với U.19 Myanmar. Nếu U.19 Thái Lan thua U.19 Việt Nam và U.19 Malaysia thắng U.19 Myanmar thì 2 đội Thái Lan, Malaysia có cùng 4 điểm và sẽ xét đến hiệu số phụ bàn thắng bại để chọn đội vào chung kết với Việt Nam, đội còn lại tranh hạng ba với Myanmar.Tâm điểm sẽ là trận đại chiến U.19 Việt Nam và U.19 Thái Lan. “Chúng tôi từng đối đầu nhau và Thái Lan có1 trận hòa, 1 trận thua tại U.19 AFF Cup. Tôi đặt mục tiêu có 1 chiến thắng trước U.19 Việt Nam. Qua 2 trận, U.19 Việt Nam cho thấy lối đá tiến bộ hơn so với lần gặp nhau tháng rồi, đặc biệt lối chơi tấn công cống hiến và tinh thần mạnh mẽ. Vì thế, chúng tôi sẽ cẩn trọng để phá lối chơi của chủ nhà”, HLV Salvador Garcia của U.19 Thái Lan nói. Trong khi đó, BHL U.23 Việt Nam tiếp tục trao cơ hội cho các tuyển thủ ít được ra sân cọ xát nhưng cũng khẳng định sẽ chơi ra trò trước Thái Lan. “Đấu với đối thủ hàng đầu khu vực như Thái Lan là dịp để các cầu thủ trẻ Việt Nam cải thiện vấn đề tâm lý thi đấu. Các cầu thủ mới bổ sung thể hiện được tiềm năng và sự tiến bộ nhưng rất cần sự ổn định. Nỗi lo của tôi là ở hàng phòng ngự, sẽ tập trung cải thiện trước người Thái vốn rất bản lĩnh”, HLV Đinh Thế Nam cho biết.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/pwivoviu/2022_08_08/20b1-7675.jpg', '2022-08-09', '1');
INSERT INTO `quanlytintuc`.`baiviet` (`tieude`, `mataikhoan`, `machude`, `mota`, `noidung`, `anhnen`, `ngaydang`, `trangthai`) VALUES ('M.U ‘thất thểu’ trở lại thị trường chuyển nhượng, ra sức chiêu mộ Adrien Rabiot', '1', '6', 'M.U đang ra sức chiêu mộ tiền vệ Adrien Rabiot sau màn trình diễn tệ hại trong trận ra quân Ngoại hạng Anh.', 'M.U đã trở lại tham gia thị trường chuyển nhượng với ý định tìm kiếm bổ sung cầu thủ ở các giải đấu Ý. Mục tiêu của “Quỷ đỏ” là Adrien Rabiot của Juventus, theo tờ The Athletic.Hợp đồng của tuyển thủ Pháp với Juventus hết hạn vào tháng 6 năm tới và “Lão phu nhân thành Turin” không muốn mất tiền vệ 27 tuổi này miễn phí, mặc dù đã có được Rabiot từ PSG vào năm 2019 mà không tốn xu nào.Đội bóng chủ sân Old Trafford phải gấp gáp tiến hành đàm phán với phía Juventus sau khi việc theo đuổi Frenkie De Jong của Barcelona đang gặp khó khăn. Cầu thủ người Hà Lan là mục tiêu của HLV Erik ten Hag, người biết rõ học trò cũ từ thời còn ở Ajax.De Jong nhiều khả năng sẽ không gia nhập đội bóng Ngoại hạng Anh bất chấp sự khăng khăng, với việc chủ tịch Joan Laporta của Barcelona tuần trước xác nhận mong muốn De Jong ở lại.', 'https://image.thanhnien.vn/w2048/Uploaded/2022/cjhwpdhnw/2022_08_09/rabiot-afp-5732.jpeg', '2022-08-09', '1');


INSERT INTO `quanlytintuc`.`binhluan` (`mataikhoan`, `mabaiviet`, `noidung`, `ngaygui`) VALUES ('2', '1', 'Bài viết hay quá!', '2022-08-13');
INSERT INTO `quanlytintuc`.`binhluan` (`mataikhoan`, `mabaiviet`, `noidung`, `ngaygui`) VALUES ('3', '1', 'Bài viết tuyệt!', '2022-08-13');
INSERT INTO `quanlytintuc`.`binhluan` (`mataikhoan`, `mabaiviet`, `noidung`, `ngaygui`) VALUES ('4', '1', 'Cảm ơn anh!', '2022-08-13');
INSERT INTO `quanlytintuc`.`binhluan` (`mataikhoan`, `mabaiviet`, `noidung`, `ngaygui`) VALUES ('2', '2', 'Bài viết hay quá!', '2022-08-13');
